ReversiMvcApp/Models/Game.cs
using System.ComponentModel.DataAnnotations;

namespace ReversiMvcApp.Models
{
    public enum Colour { None, White, Black };

    public class Game
    {
        [Key]
        public string Token { get; set; }
        public string Description { get; set; }
        public string Player1Token { get; set; }
        public string Player2Token { get; set; }
        public string Board { get; set; }
        public Colour Turn { get; set; }
        public bool IsFinished { get; set; }
        public Colour Winner { get; set; }
    }
}

ReversiMvcApp/Models/ViewModels/GameViewModel.cs
namespace ReversiMvcApp.Models.ViewModels
{
    public class GameViewModel
    {
        public Game Game { get; set; }
        public string PlayerColour { get; set; }
        public string PlayerToken { get; set; }
        public string Player1Name { get; set; }
        public string Player2Name { get; set; }
        public string ApiURI { get; set; }
        public string ApiToken { get; set; }

        public GameViewModel(Game game, string playerColour, string playerToken, string player1Name, string player2Name, string apiURI, string apiToken)
        {
            Game = game;
            PlayerColour = playerColour;
            PlayerToken = playerToken;
            Player1Name = player1Name;
            Player2Name = player2Name;
            ApiURI = apiURI;
            ApiToken = apiToken;
        }
    }
}

ReversiMvcApp/Models/ViewModels/WaitingForPlayerViewModel.cs
namespace ReversiMvcApp.Models.ViewModels
{
    public class WaitingForPlayerViewModel
    {
        public Game Game { get; set; }
        public string ApiURI { get; set; }
        public string ApiToken { get; set; }

        public WaitingForPlayerViewModel(Game game, string apiURI, string apiToken)
        {
            Game = game;
            ApiURI = apiURI;
            ApiToken = apiToken;
        }
    }
}

ReversiMvcApp/Controllers/GamesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using ReversiMvcApp.Data;
using ReversiMvcApp.Models;
using ReversiMvcApp.Models.ViewModels;

namespace ReversiMvcApp.Controllers
{
    [Authorize(Policy = ApplicationPolicies.PlayerOnly)]
    public class GamesController : Controller
    {
        private readonly ReversiDbContext _context;
        private readonly IReversiApi _api;
        private readonly string _apiUri;
        private readonly UserManager<IdentityUser> _userManager;

        public GamesController(ReversiDbContext context, UserManager<IdentityUser> userManager, IReversiApi api, IOptions<Apis> apis)
        {
            _context = context;
            _api = api;
            _apiUri = apis.Value.Reversi.Uri;
            _userManager = userManager;
        }


        // GET: Games
        public async Task<IActionResult> Index()
        {
            // redirect to game if there's still an unfinished game
            Game unfinishedGame = await GetUnfinishedGame();
            if (unfinishedGame != null)
                return RedirectToAction(nameof(Play), new { token = unfinishedGame.Token });

            IList<Game> games = (await _api.GetGamesLookingForPlayers()).ToList<Game>();
            return View(games);
        }


        /// <summary>
        /// GET: Games/{token}
        /// </summary>
        /// <param name="token"></param>
        /// <returns></returns>
        [HttpGet("Games/{token}")]
        public async Task<IActionResult> Play(string token)
        {
            // game must exist
            if (string.IsNullOrEmpty(token))
                return NotFound();
            Game game = await _api.GetGame(token);
            if (game == null)
                return NotFound();

            // player must be player in game
            string playerToken = GetPlayerToken();
            if (game.Player1Token != playerToken && game.Player2Token != playerToken)
                return RedirectToAction(nameof(Index));

            string apiToken = await GetApiTokenForPlayer(playerToken);

            // if game not started yet, go to waiting view
            if (game.Player1Token == null || game.Player2Token == null)
                return View("WaitingForPlayer", new WaitingForPlayerViewModel(game, _apiUri, apiToken));

            // get player info
            string currentPlayerName = User.Identity.Name;
            string colour;
            string whiteName;
            string blackName;
            if(playerToken == game.Player1Token)
            {
                colour = "White";
                whiteName = currentPlayerName;
                blackName = GetPlayerName(game.Player2Token);
            }
            else
            {
                colour = "Black";
                blackName = currentPlayerName;
                whiteName = GetPlayerName(game.Player1Token);
            }

            return View("Game", new GameViewModel(game, colour, GetPlayerToken(), whiteName, blackName, _apiUri, apiToken));
        }


        /// <summary>
        /// GET: Games/{token}/Join
        /// </summary>
        /// <param name="game"></param>
        /// <returns></returns>
        [HttpGet("Games/{token}/Join")]
        public async Task<IActionResult> Join(string token)
        {
            string playerToken = GetPlayerToken();
            Game joinedGame = await _api.JoinGame(token, playerToken);
            return RedirectToAction(nameof(Play), new { token = joinedGame.Token });
        }


        // GET: Games/Create
        [HttpGet("Games/Create")]
        public async Task<IActionResult> Create()
        {
            // redirect to game if there's still an unfinished game
            Game unfinishedGame = await GetUnfinishedGame();
            if (unfinishedGame != null)
                return RedirectToAction(nameof(Play), new { token = unfinishedGame.Token });

            return View();
        }


        // POST: Games/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Description")] Game game)
        {
            if (ModelState.IsValid)
            {
                game.Player1Token = GetPlayerToken();
                // create in api
                Game newGame = await _api.CreateGame(game);
                // monitor locally too
                _context.RunningGames.Add(new RunningGame(newGame.Token));
                await _context.SaveChangesAsync();
                
                return RedirectToAction(nameof(Index));
            }
            return View(game);
        }


        /// <summary>
        /// Finish current game
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        [HttpGet("Games/{token}/Finish")]
        public async Task<IActionResult> Finish(string token)
        {
            if (token == null)
                return NotFound();
            RunningGame runningGame = await _context.RunningGames.FindAsync(token);

            // get finished game data
            Game game = await _api.GetGame(token);
            if (game == null || !game.IsFinished)
                return NotFound();

            // get players
            Player whitePlayer = await _context.Players.FindAsync(game.Player1Token);
            if (whitePlayer == null)
            {
                whitePlayer = new Player(game.Player1Token);
                _context.Players.Add(whitePlayer);
            }
            Player blackPlayer = await _context.Players.FindAsync(game.Player2Token);
            if (blackPlayer == null)
            {
                blackPlayer = new Player(game.Player2Token);
                _context.Players.Add(blackPlayer);
            }

            // mark winner and check if current player won
            var viewModel = new FinishedGameViewModel(GameResult.Lost);
            string playerToken = GetPlayerToken();
            switch (game.Winner)
            {
                case Colour.White:
                    whitePlayer.TimesWon++;
                    blackPlayer.TimesLost++;
                    if (game.Player1Token == playerToken)
                        viewModel.Result = GameResult.Won;
                    break;
                case Colour.Black:
                    whitePlayer.TimesLost++;
                    blackPlayer.TimesWon++;
                    if (game.Player2Token == playerToken)
                        viewModel.Result = GameResult.Won;
                    break;
                case Colour.None:
                    whitePlayer.TimesTied++;
                    blackPlayer.TimesTied++;
                    viewModel.Result = GameResult.Tied;
                    break;
            }

            // if the game was still running, mark it as not running
            // and save new score stats
            if (runningGame != null)
            {
                // remove from running games so it can't be marked as won again
                _context.RunningGames.Remove(runningGame);
                await _context.SaveChangesAsync();
            }

            return View(viewModel);
        }



        /// <summary>
        /// Get a JWT token from the API.
        /// The client can use this JWT token to communicate their game actions directly with the API.
        /// </summary>
        /// <param name="playerToken">The user ID</param>
        /// <returns>
        /// The token contains: 
        /// - the player token (player identifier)
        /// - which role(s) the player has (permission security)
        /// </returns>
        private async Task<string> GetApiTokenForPlayer(string playerToken)
        {
            var roles = new List<string>();
            var roleClaims = User.Claims.Where(claim => claim.Type.Equals(ClaimTypes.Role));
            foreach (Claim role in roleClaims)
                roles.Add(role.Value);
            return await _api.GetApiTokenForPlayer(playerToken, roles);
        }

        /// <summary>
        /// Get name for given ID
        /// </summary>
        /// <param name="playerToken"></param>
        /// <returns></returns>
        private string GetPlayerName(string playerToken)
        {
            var user = _userManager.Users.Where(user => user.Id == playerToken).FirstOrDefault();
            return user?.UserName;
        }

        /// <summary>
        /// If the given game exists
        /// </summary>
        /// <param name="token"></param>
        /// <returns></returns>
        private async Task<bool> GameExists(string token)
        {
            return await _api.GetGame(token) != null;
        }

        /// <summary>
        /// If the currently logged in player is playing in a still ongoing game,
        /// this method will return that game.
        /// If there's multiple ongoing games it will return the first one.
        /// If there's no ongoing games for the player it will return null.
        /// </summary>
        /// <returns>Game|null depending if ongoing game is available for logged in player</returns>
        private async Task<Game> GetUnfinishedGame()
        {
            string playerToken = GetPlayerToken();
            IEnumerable<Game> gamesPlaying = await _api.GetGamesWithPlayer(playerToken);
            return gamesPlaying.FirstOrDefault(g => g.IsFinished == false);
        }

        /// <summary>
        /// Gets token for currently logged in player
        /// </summary>

ReversiMvcApp/Views/Games/Create.cshtml
@model ReversiMvcApp.Models.Game

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Game</h4>
<hr/>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List of Games</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ReversiMvcApp/Views/Games/Delete.cshtml
@model ReversiMvcApp.Models.Game

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Game</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Player1Token)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Player1Token)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Player2Token)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Player2Token)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Board)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Board)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Turn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Turn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsFinished)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsFinished)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Token" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ReversiMvcApp/Views/Games/Details.cshtml
@model ReversiMvcApp.Models.Game

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Game</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Player1Token)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Player1Token)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Player2Token)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Player2Token)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Board)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Board)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Turn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Turn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsFinished)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsFinished)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Token">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ReversiMvcApp/Views/Games/Edit.cshtml
@model ReversiMvcApp.Models.Game

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Game</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Token" />
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Player1Token" class="control-label"></label>
                <input asp-for="Player1Token" class="form-control" />
                <span asp-validation-for="Player1Token" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Player2Token" class="control-label"></label>
                <input asp-for="Player2Token" class="form-control" />
                <span asp-validation-for="Player2Token" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Board" class="control-label"></label>
                <input asp-for="Board" class="form-control" />
                <span asp-validation-for="Board" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Turn" class="control-label"></label>
                <select asp-for="Turn" class="form-control"></select>
                <span asp-validation-for="Turn" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsFinished" /> @Html.DisplayNameFor(model => model.IsFinished)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ReversiMvcApp/Views/Games/Finish.cshtml
@using ReversiMvcApp.Models.ViewModels
@model FinishedGameViewModel
@{
    ViewData["Title"] = $"You {Model.Result.ToString()!}";
}

<div class="finished finished__@Model.Result.ToString().ToLower()">
    @if(Model.Result == GameResult.Won)
    {
        <h1 class="finished--title">You Win!!!</h1>
    }
    else if(Model.Result == GameResult.Lost)
    {
        <h1 class="finished--title">You Lose!!!</h1>
    }
    else if(Model.Result == GameResult.Tied)
    {
        <h1 class="finished--title">You Tied!!!</h1>
    }
    <a class="finished--continue" asp-controller="Games" asp-action="Index">Continue</a>
</div>

ReversiMvcApp/Views/Games/Game.cshtml
@model ReversiMvcApp.Models.ViewModels.GameViewModel

@{
    ViewData["Title"] = "Play";
}

<link href="@Url.Content("~/css/style.min.css")" rel="stylesheet" type="text/css" />

<h1>Game: @Model.Game.Description</h1>

<div class="row">
    <div class="col playerlist__container">
    </div>
</div>
<div class="row">
    <div class="col-md-6 col-12">
        <div class="board__container halfofcontainer halfofcontainer--withheight"></div>
    </div>
    <div class="col-md-6 col-12 catcontainer">
    </div>
</div>

<div class="row">
    <div class="col-12">
        <h2 class=" mt-5">Stats</h2>
    </div>
    <div class="col-12">
        <canvas id="discs-count-chart"></canvas>
    </div>
    <div class="col-12">
        <canvas id="conquered-chart"></canvas>
    </div>
</div>

@section Scripts
{
    <script type="text/javascript" src="~/js/app.js" asp-append-version="true"></script>
    <script type="text/javascript" src="~/js/templates.js" asp-append-version="true"></script>
    <script type="text/javascript">
        document.addEventListener("DOMContentLoaded", () =>
        {
            const playerList = document.getElementsByClassName("playerlist__container")[0]
            Game.PlayerList.init(playerList, "@Model.Player1Name", "@Model.Player2Name", Game.Data.GameState.@Model.PlayerColour)
            Game.Data.init(Game.Data.Environment.Production, "@Model.ApiURI", "@Model.ApiToken")
            Game.init('@Model.Game.Token', Game.Data.GameState.@Model.PlayerColour, '@Model.PlayerToken')

            const board = document.getElementsByClassName("board__container")[0]
            Game.initBoard(board)

            Cat.initTemplates(".catcontainer")

            // init charts
            Game.Stats.initDiscCount(document.getElementById("discs-count-chart"), "@Model.Player1Name", "@Model.Player2Name")
            Game.Stats.initConqueredChart(document.getElementById("conquered-chart"), "@Model.Player1Name", "@Model.Player2Name")
        })
    </script>
}

ReversiMvcApp/Views/Games/Index.cshtml
@model IEnumerable<ReversiMvcApp.Models.Game>

@{
    ViewData["Title"] = "Games";
}

<h1>Index</h1>

@if(Model.Count() == 0)
{
    <p>
    There are no games looking for players.
    Create one yourself to start playing <a asp-action="Create">here</a>.
    </p>
}
else
{
    <p>
        <a asp-action="Create">Create New Game</a>
    </p>

    <ul class="list-group">
        @foreach (Game item in Model)
        {
            <li class="list-group-item">
                <span>@Html.DisplayFor(modelItem => item.Description)</span>
                <a class="btn btn-primary" asp-action="Join" asp-route-token="@item.Token">Join</a>
            </li>
        }
    </ul>

}

ReversiMvcApp/Views/Games/WaitingForPlayer.cshtml
@model ReversiMvcApp.Models.ViewModels.WaitingForPlayerViewModel
@{
    ViewData["Title"] = "Waiting for players";
}

<link href="@Url.Content("~/css/style.min.css")" rel="stylesheet" type="text/css" />

<h1>Game: @Model.Game.Description</h1>
<p class="waitingforplayers"><b class="loadingdots">Waiting for opponent</b></p>
<div class="catcontainer"></div>

@section Scripts
{
    <script type="text/javascript" src="~/js/app.js" asp-append-version="true"></script>
    <script type="text/javascript" src="~/js/templates.js" asp-append-version="true"></script>
    <script type="text/javascript">
        document.addEventListener("DOMContentLoaded", () =>
        {
            Game.Data.init(Game.Data.Environment.Production, "@Model.ApiURI", "@Model.ApiToken")
            Game.Waiting.init("@Model.Game.Token")
            Cat.initTemplates(".catcontainer")
        })
    </script>
}